
BugGrabberDB = {
["lastSanitation"] = 3,
["session"] = 589,
["errors"] = {
{
["message"] = "...Blizzard_ChatFrameBase/Classic/FloatingChatFrame.lua:727: attempt to index local 'self' (a nil value)",
["time"] = "2025/10/19 12:56:11",
["locals"] = "self = nil\nchatFrame = ChatFrame5 {\n isLayoutDirty = true\n oldestFadingLineTimestamp = 5547.825000\n tellTimer = 5544.003000\n fadeDurationSecs = 3\n shouldFadeAfterInactivity = true\n buttonSide = \"left\"\n textIsCopyable = false\n ResizeButton = ChatFrame5ResizeButton {\n }\n overrideFadeTimestamp = 5547.825000\n isScrollingMessageFrame = true\n name = \"Chat 5\"\n isUninteractable = false\n minimizeButton = ChatFrame5MinimizeButton {\n }\n buttonFrame = ChatFrame5ButtonFrame {\n }\n alternativeDefaultLanguage = \"Orcish\"\n isInitialized = 1\n hasOwnFontObject = true\n allowScroll = true\n oldAlpha = 0\n channelList = <table> {\n }\n FontStringContainer = Frame {\n }\n messageTypeList = <table> {\n }\n flashTimer = 0\n timeVisibleSecs = 120\n fontObject = table: 0000023CDEB1A250 {\n }\n zoneChannelList = <table> {\n }\n insertMode = 2\n defaultLanguage = \"Orcish\"\n Background = ChatFrame5Background {\n }\n isDisplayDirty = true\n onDisplayRefreshedCallbacks = <table> {\n }\n visibleLines = <table> {\n }\n scrollOffset = 0\n historyBuffer = <table> {\n }\n ScrollToBottomButton = Button {\n }\n clickAnywhereButton = ChatFrame5ClickAnywhereButton {\n }\n PratTextures = <table> {\n }\n editBox = ChatFrame5EditBox {\n }\n isLocked = true\n}\nfontSize = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = nil\n(*temporary) = \"attempt to index local 'self' (a nil value)\"\n",
["stack"] = "[Interface/AddOns/Blizzard_ChatFrameBase/Classic/FloatingChatFrame.lua]:727: in function <...Blizzard_ChatFrameBase/Classic/FloatingChatFrame.lua:722>\n[C]: in function 'FCF_SetChatWindowFontSize'\n[Interface/AddOns/Prat-3.0-3.9.67/modules/Font.lua]:765: in function 'SetFontSize'\n[Interface/AddOns/Prat-3.0-3.9.67/modules/Font.lua]:753: in function 'ConfigureAllChatFrames'\n[Interface/AddOns/Prat-3.0-3.9.67/modules/ChatFrames.lua]:636: in function <Interface/AddOns/Prat-3.0/modules/ChatFrames.lua:630>\n[tail call]: ?\n[C]: in function 'FloatingChatFrame_UpdateBackgroundAnchors'\n[Interface/AddOns/Blizzard_CombatLog/Classic/Blizzard_CombatLog.lua]:3302: in function <...ns/Blizzard_CombatLog/Classic/Blizzard_CombatLog.lua:3288>\n[Interface/AddOns/Blizzard_CombatLog/Classic/Blizzard_CombatLog.lua]:3355: in function 'FCF_DockUpdate'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager.lua]:1036: in function 'UIParentManageFramePositions'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager.lua]:325: in function <...IParentPanelManager/Classic/UIParentPanelManager.lua:312>\n[C]: in function 'SetAttribute'\n[Interface/AddOns/Blizzard_UIParentPanelManager/Classic/UIParentPanelManager.lua]:1047: in function <...IParentPanelManager/Classic/UIParentPanelManager.lua:1045>\n[C]: in function 'UIParent_ManageFramePositions'\n[Interface/AddOns/Blizzard_BuffFrame/Classic/BuffFrame.lua]:364: in function 'BuffFrame_UpdateAllBuffAnchors'\n[Interface/AddOns/Blizzard_BuffFrame/Classic/BuffFrame.lua]:105: in function 'BuffFrame_Update'\n[Interface/AddOns/Blizzard_SettingsDefinitions_Frame/Classic/InterfaceOverrides.lua]:103: in function <...ingsDefinitions_Frame/Classic/InterfaceOverrides.lua:102>\n[C]: ?\n[Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua]:144: in function <...e/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua:143>\n[C]: ?\n[Interface/AddOns/Blizzard_SharedXMLBase/CallbackRegistry.lua]:147: in function 'TriggerEvent'\n[Interface/AddOns/Blizzard_SharedXMLBase/CvarUtil.lua]:118: in function <Interface/AddOns/Blizzard_SharedXMLBase/CvarUtil.lua:110>",
["session"] = 587,
["counter"] = 1,
},
},
}
